# Configuración de soporte para cf-keys
github: [choco-latito29]

# Opciones adicionales (descomenta y edita si tienes cuenta en estas plataformas)
# ko_fi: choco_latito29
# buy_me_a_coffee: choco_latito29
# custom: ["https://paypal.me/tu_enlace"]
